export const ROUTES = {
  LOGIN: "/login",
  SIGNUP: "/signup",
  VERIFY_EMAIL: "/verify-email",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  ONBOARD: "/onboard",
  CALLBACK: "/auth/callback",
  DASHBOARD: "/dashboard",
  ANALYTICS: "/analytics",
  GOALS: "/goals",
  TRANSACTIONS: "/transactions",
  INVOICES: "/invoices",
  VENDORS: "/vendors",
  PAYMENTS: "/payments",
  BUDGETS: "/budgets",
  APPROVALS: "/approvals",
  ALERTS: "/alerts",
  REPORTS: "/reports",
  EMAILS: "/emails",
  SETTINGS: "/settings",
} as const;

export const STATUS_COLORS = {
  DRAFT: "muted",
  PENDING_APPROVAL: "warning",
  APPROVED: "info",
  REJECTED: "danger",
  PAID: "success",
  OVERDUE: "danger",
  VOIDED: "muted",
  PENDING: "warning",
  CLEARED: "success",
  RECONCILED: "success",
  CREDIT: "success",
  DEBIT: "danger",
} as const;
